import { Router } from 'express';
import { getRecommendations, recordRecommendationEvent } from '../services/recommendations/service';
import prisma from '../config/prisma';
const router = Router();
type RecommendationEventInput = { trackingToken?: unknown; eventType?: unknown };
router.get('/lessons/:lessonId', async (req, res) => { const courseId = String(req.query.courseId || ''); const limit = Number(req.query.limit || 5); if (!courseId || !Number.isFinite(limit) || limit < 1 || limit > 5) return res.status(400).json({ code: 400, message: 'courseId/limit 参数无效', data: null }); try { return res.json({ code: 200, message: 'success', data: await getRecommendations(req.user.id, { courseId, lessonId: req.params.lessonId, limit, scene: 'lesson' }) }); } catch { return res.status(404).json({ code: 404, message: '小节不存在', data: null }); } });
router.get('/review', async (req, res) => { let courseId = String(req.query.courseId || ''); const limit = Number(req.query.limit || 5); if (!Number.isFinite(limit) || limit < 1 || limit > 5) return res.status(400).json({ code: 400, message: 'limit 参数无效', data: null }); if (!courseId) { const enrolled = await prisma.courses_progress.findFirst({ where: { user_id: req.user.id, is_delete: 0 }, orderBy: { last_learned_at: 'desc' }, select: { course_id: true } }); courseId = enrolled?.course_id || ''; } if (!courseId) { const firstCourse = await prisma.courses.findFirst({ where: { is_delete: 0 }, orderBy: [{ level: 'asc' }, { created_at: 'asc' }], select: { id: true } }); courseId = firstCourse?.id || ''; } if (!courseId) return res.json({ code: 200, message: 'success', data: { feedId: '', scene: 'review', mode: 'cold_start', items: [] } }); return res.json({ code: 200, message: 'success', data: await getRecommendations(req.user.id, { courseId, limit, scene: 'review' }) }); });
router.post('/events', async (req, res) => { try { const events: RecommendationEventInput[] = Array.isArray(req.body.events) ? req.body.events : [req.body]; if (!events.length || events.length > 20) return res.status(400).json({ code: 400, message: '事件数量无效', data: null }); for (const event of events) { if (typeof event.trackingToken !== 'string' || typeof event.eventType !== 'string' || !['impression','clicked','review_started','review_completed'].includes(event.eventType)) return res.status(400).json({ code: 400, message: '事件参数无效', data: null }); } const results = await Promise.all(events.map((event) => recordRecommendationEvent({ userId: req.user.id, token: event.trackingToken as string, eventType: event.eventType as string }))); return res.json({ code: 200, message: 'success', data: { recorded: results.length } }); } catch { return res.status(400).json({ code: 400, message: 'trackingToken 无效', data: null }); } });
export default router;
